op-en-app-server:
  image: leofidjeland/op-en-app-server
  ports:
   - "5000:5000"
  links:
   - mosquitto
influx:
  image: tutum/influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
grafana:
  image: grafana/grafana
  ports:
    - "3000:3000"
mosquitto:
  image: ansi/mosquitto
  ports:
    - "1883:1883"
node-red:
  image: node-red
  ports:
    - "1880:1880"
  volumes:
   - node-red:/root/.node-red
